baseURL: "https://bigtreetrading.com"
languageCode: en-us
title: BigTree Trading Group
theme: PaperMod
paginate: 6

params:
  env: production
  homeInfoParams:
    Content: "Welcome to BigTree Trading. Our goal is to help institutions and individuals build stronger portfolios by combining traditional and alternative investments."

  socialIcons:
    - name: other
      url: "https://one.exnesstrack.net/a/s0cxkwr4tg?platform=mobile&pid=mobile_share"
    - name: twitter
      url: "https://twitter.com/nhagiaodich_com"
    - name: tiktok
      url: "https://tiktok.com/@nhagiaodich_com"
    - name: facebook
      url: "https://www.facebook.com/nhagiaodichcom"
    - name: youtube
      url: "https://www.youtube.com/@nhagiaodich_com"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
    - identifier: contact
      name: Contact us
      url: /contactus/
      weight: 50
    